<small><small><i>
All the IPython Notebooks in this lecture series by Dr. Milan Parmar are available @ **[GitHub](https://github.com/milaan9/09_Python_NumPy_Module)**
</i></small></small>

# Python NumPy

In this class, you will learn various NumPy concepts like how to install NumPy, arrays, functions, matrix multiplication, etc. This NumPy in Python tutorial will help you learn all Python NumPy basics.

**[Numpy](http://www.numpy.org/)** (‘Numerical Python’) is the core open source library for scientific computing in Python. It is a Linear Algebra Library for Python, it is so important for Finance with Python. It is a very useful library to perform mathematical and statistical operations in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. In this part, we will review the essential functions that you need to know for the tutorial on 'TensorFlow.'

## Why use NumPy?

NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping. On top of that, NumPy is fast. In fact, TensorFlow and Scikit learn to use NumPy array to compute the matrix multiplication in the back end.

# Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## NumPy Array Types:

<div>
<img src="images/array.png" width="700"/>
</div>

## Create a NumPy Array

Simplest way to create an array in Numpy is to use Python List

### Load in NumPy Library

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

To convert python list to a numpy array by using the object **`np.array`**.

In [3]:
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4])

In practice, there is no need to declare a Python List. The operation can be combined.

In [4]:
my_list1  = np.array([1,2,3,4])
my_list1

array([1, 2, 3, 4])

>**NOTE:** Numpy documentation states use of **`np.ndarray`** to create an array. However, this the recommended method

You can also create a numpy array from a Tuple

In [5]:
my_list2 = np.array(range(1,5))
my_list2

array([1, 2, 3, 4])

## Numpy Array basics 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets **`[]`**:

In [6]:
a = np.array([1,2,3]) # Create a 1D array
print(a) 
print(type(a))  # Prints "<class 'numpy.ndarray'>"

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # Create a 2D array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Create a 2D array with 3 rows
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Get Dimension
a.ndim

1

In [10]:
# Get Shape
b.shape

(2, 3)

In [11]:
# Get Size
a.itemsize

4

In [12]:
# Get Size
b.itemsize

8

In [13]:
# Get total size
a.nbytes  # a.nbytes = a.size * a.itemsize

12

In [14]:
# Get number of elements
a.size

3

You can read all about numpy datatypes in this **[documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)**.

### Random number

#### `rand`
Random values in a given shape from a uniform distribution over [0, 1)

In [22]:
np.random.rand(3)

array([0.22672978, 0.55283762, 0.10276143])

In [23]:
np.random.rand(3,5)

array([[0.2559205 , 0.60786967, 0.83770503, 0.45359369, 0.27764243],
       [0.38209653, 0.44225798, 0.63158859, 0.81893678, 0.79823164],
       [0.69791535, 0.69343173, 0.04763428, 0.1097501 , 0.30920635]])

#### `randint`
Return random integers from **low** (inclusive) to **high** (exclusive).

In [27]:
np.random.randint(2,100)

85

In [28]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  2,  2],
       [ 5,  3,  2],
       [ 6, -1,  2]])

### Array Attributes and Methods


In [32]:
rana = np.random.randint(1,10,8)
rana

array([5, 9, 9, 2, 2, 3, 6, 1])

#### `max`, `min`, `argmax`, `argmin`

In [33]:
rana

array([5, 9, 9, 2, 2, 3, 6, 1])

In [34]:
rana.max()

9

In [35]:
rana.argmax()

1

In [36]:
rana.min()

1

In [37]:
rana.argmin()

7

### Numpy also provides many functions to create arrays:

In [38]:
# Generating Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
# All 0s matrix
np.zeros((2,3))  # pass a tupple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# Generating Zeros
np.ones(3)       # one function

array([1., 1., 1.])

In [1]:

np.ones(3)*5

NameError: name 'np' is not defined

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# NumPy Basics

Below is a compilation of functions, and NumPy uses that will be helpful when using numpy further. You can also check out the `NumPy Cheat Sheet Data Analysis in Python.pdf` in the Lessons folder. 

### NumPy Basics

| Operator | Description |
|:---- |:---- |
| **`np.array([1,2,3])`**           | **1d array** | 
| **`np.array([(1,2,3),(4,5,6)])`** | **2d array** | 
| **`np.arange(start,stop,step)`**  | **range array**  | 

### Placeholders

| Operator | Description |
|:---- |:---- |
| **`np.linspace(0,2,9)`**      | **Add evenly spaced values btw interval to array of length** |
| **`np.zeros((1,2))`**         | **Create and array filled with zeros** |
| **`np.ones((1,2))`**          | **Creates an array filled with ones** |
| **`np.random.random((5,5))`** | **Creates random array** |
| **`np.empty((2,2))`**         | **Creates an empty array** |

### Array

| Operator | Description |
|:---- |:---- |
| **`array.shape`**        | **Dimensions (Rows,Columns)** |
| **`len(array)`**         | **Length of Array** |
| **`array.ndim`**         | **Number of Array Dimensions** |
| **`array.dtype`**        | **Data Type** |
| **`array.astype(type)`** | **Converts to Data Type** |
| **`type(array)`**        | **Type of Array** |

### Copying/Sorting

| Operator | Description |
|:---- |:---- |
| **`np.copy(array)`**       | **Creates copy of array** |
| **`other = array.copy()`** | **Creates deep copy of array** |
| **`array.sort()`**         | **Sorts an array** |
| **`array.sort(axis=0)`**   | **Sorts axis of array** |

## Array Manipulation

### Adding or Removing Elements

| Operator | Description |
|:---- |:---- |
| **`np.append(a,b)`**               | **Append items to array** |
| **`np.insert(array, 1, 2, axis)`** | **Insert items into array at axis 0 or 1** |
| **`np.resize((2,4))`**             | **Resize array to shape(2,4)** |
| **`np.delete(array,1,axis)`**      | **Deletes items from array** |

### Combining Arrays

| Operator | Description |
|:---- |:---- |
| **`np.concatenate((a,b),axis=0)`** | **Split an array into multiple sub-arrays.** |
| **`np.vstack((a,b))`**             | **Split an array in sub-arrays of (nearly) identical size** |
| **`np.hstack((a,b))`**             | **Split the array horizontally at 3rd index** |

### More

| Operator | Description |
|:---- |:---- |
| **`other = ndarray.flatten()`**       | **Flattens a 2d array to 1d** |
| **`array = np.transpose(other)`**     | **Transpose array** |
| **`array.T`**                         | **Transpose array** |
| **`inverse = np.linalg.inv(matrix)`** | **Inverse of a given matrix** |

## Slicing and Subsetting

| Operator | Description |
|:---- |:---- |
| **`array[i]`**        | **1d array at index i** |
| **`array[i,j]`**      | **2d array at index[i][j]** |
| **`array[i<4]`**      | **Boolean Indexing, see Tricks** |
| **`array[0:3]`**      | **Select items of index 0, 1 and 2** |
| **`array[0:2,1]`**    | **Select items of rows 0 and 1 at column 1** |
| **`array[:1]`**       | **Select items of row 0 (equals array[0:1, :])** |
| **`array[1:2, :]`**   | **Select items of row 1** |
| **`[comment]: <> (`** | **array[1,...]** |
| **`array[ : :-1]`**   | **Reverses array** |

## Mathematics

### Operations

| Operator | Description |
|:---- |:---- |
| **`np.add(x,y)`**        | **Addition** |
| **`np.substract(x,y)`**  | **Subtraction** |
| **`np.divide(x,y)`**     | **Division** |
| **`np.multiply(x,y)`**   | **Multiplication** |
| **`np.sqrt(x)`**         | **Square Root** |
| **`np.sin(x)`**          | **Element-wise sine** |
| **`np.cos(x)`**          | **Element-wise cosine** |
| **`np.log(x)`**          | **Element-wise natural log** |
| **`np.dot(x,y)`**        | **Dot product** |
| **`np.roots([1,0,-4])`** | **Roots of a given polynomial coefficients** |

### Comparison

| Operator | Description |
|:----: |:---- |
| **`==`** | **Equal** |
| **`!=`** | **Not equal** |
| **`<`**  | **Smaller than** |
| **`>`**  | **Greater than** |
| **`<=`** | **Smaller than or equal** |
| **`>=`** | **Greater than or equal** |
| **`np.array_equal(x,y)`** | **Array-wise comparison** |

## Basic Statistics

| Operator | Description |
|:---- |:---- |
| **`np.mean(array)`**   | **Mean** |
| **`np.median(array)`** | **Median** |
| **`array.corrcoef()`** | **Correlation Coefficient** |
| **`np.std(array)`**    | **Standard Deviation** |

### More

| Operator | Description |
|:---- |:---- |
| **`array.sum()`**          | **Array-wise sum** |
| **`array.min()`**          | **Array-wise minimum value** |
| **`array.max(axis=0)`**    | **Maximum value of specified axis** |
| **`array.cumsum(axis=0)`** | **Cumulative sum of specified axis** |