> *The creation of the lessons in this unit relied heavily on the existing lessons created by Mrs. FitzZaland as well as the [lecture series](https://github.com/milaan9/09_Python_NumPy_Module) produced by Dr. Milaan Parmar. Additionally, these lessons have largely been modelled off of the book [Think Python](https://open.umn.edu/opentextbooks/textbooks/43) by Allen Downey.*

# NumPy

This NumPy lesson will help you learn all the NumPy basics.

If it would be beneficial for your learning, feel free to **take a look at [this video](https://www.youtube.com/watch?v=xECXZ3tyONo) on NumPy.**

<div class="alert alert-info"><h4>Tasks</h4><p>Alert boxes like this will provide you with tasks that you must do while going through this lesson.</p></div>

**[Numpy](http://www.numpy.org/)** (‘Numerical Python’) is the core open source library for scientific computing in Python. It is a Linear Algebra Library for Python. 

It is a very useful library that allows you to perform mathematical and statistical operations in Python.

## Why use NumPy?

NumPy is memory efficiency, which allows it to handle mathematical operations between large amounts of data. Additionally, there are many built-in functions that makes programming a lot easier since you don't have to start from scratch!

# NumPy Arrays: 

A numpy array is a grid of values, all of the same type.

A numpy array is a powerful N-dimensional array object which is in the form of rows and columns. 

We can initialize NumPy arrays from nested lists and access the elements easily.

## NumPy Array Types:

<div>
<img src="images/array.png" width="700"/>
</div>

## Load the NumPy Library

Numpy is a module that can be imported like any other module:

In [1]:
import numpy as np

## Creating a NumPy Array

The simplest way to create an array in Numpy is to use lists

In [2]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

To convert python list to a numpy array by using the object **`np.array`**.

In [3]:
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4])

In practice, there is no need to declare a list first; the operation can be combined:

In [4]:
my_array  = np.array([1,2,3,4])
my_array

array([1, 2, 3, 4])

You can also create a numpy array from a tuple, which is what's created by the `range()` function:

In [5]:
my_array2 = np.array(range(1,5))
my_array2

array([1, 2, 3, 4])

## Numpy Array basics 

To create a 2D array, we can initialize numpy arrays from nested lists:

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Create a 2D array with 3 rows
my_matrix = np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Get Dimension
my_matrix.ndim

2

In [8]:
# Get Shape
my_matrix.shape

(3, 3)

You can access elements using square brackets **`[]`** remembering that indexing starts with `0` in python.

In [9]:
# Access the element in the third row and the second column
my_matrix[2,1]

8

<div class="alert alert-info"><h4>1.</h4><p>Create a new notebook and name it Lesson8_Tasks.</p></div>

<div class="alert alert-info"><h4>2.</h4><p>In your notebook, define a numpy array using the following code.</p></div>

```python
# Creating a 2D array
arr_2d = np.array([[10, 20, 30, 31, 32, 33], [40, 50, 60, 61, 62, 63]])
print("\n2D Array:")
print(arr_2d)
```
<div class="alert alert-info"><h4>3.</h4><p>And print the following attributes.</p></div>


```python
# Print some attributes
print("\nShape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data:", arr_2d.dtype)
```

### Random number

Similar to the `random` module we have previously used, NumPy can generate random numbers **and** random arrays of numbers.

#### `rand`
Random values in a given shape from a uniform distribution over [0, 1)

In [10]:
# Generate 3 random numbers
np.random.rand(3)

array([0.93042974, 0.14071076, 0.16490938])

In [11]:
# Generate a 2D array of random numbers
np.random.rand(3,5)

array([[0.43738223, 0.75087772, 0.19141358, 0.09529116, 0.33262787],
       [0.29162604, 0.24798631, 0.94816722, 0.30005522, 0.13561988],
       [0.56788581, 0.64802705, 0.77097514, 0.33379527, 0.33643366]])

#### `randint`
Return random integers from **low** (inclusive) to **high** (exclusive).

In [12]:
np.random.randint(2,100)

50

In [13]:
# Random Integer values in a 2D array
np.random.randint(-4,8, size=(3,3))

array([[ 7,  7,  7],
       [ 7,  7,  3],
       [-4,  4,  6]])

### Some more Array Attributes and Methods


In [14]:
# Generate a random array of integers
ran_arr = np.random.randint(1,10,8)
ran_arr

array([1, 9, 4, 6, 3, 8, 9, 1])

#### `max`, `min`, `argmax`, `argmin`

In [15]:
# Obtain the maximum value in the array
ran_arr.max()

9

In [16]:
# Determine the index of the maximum value in the array
ran_arr.argmax()

1

In [17]:
# The same can be done for the minimum
print(f'The smallest value in the array is {ran_arr.min()}, which is found at index {ran_arr.argmin()}.')

The smallest value in the array is 1, which is found at index 0.


### Numpy also provides many functions to create arrays:

In [18]:
# Generating an array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# Generating a 2D array of zeros
# pass a tupple to define the shape
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# Generating ones
np.ones(3)

array([1., 1., 1.])

In [21]:
# Generate an array of 5s
np.ones(3)*5

array([5., 5., 5.])

In [22]:
# Generate a 2D array of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Array indexing

Numpy offers several ways to index into arrays and accessing/changing specific elements, rows, columns, etc.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [24]:
# Generate a 1D array
a = np.arange(3,13)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
# Integer indexing
a[1]

4

In [26]:
# Slicing
a[1:4]

array([4, 5, 6])

In [27]:
# Slicing
a[:4]

array([3, 4, 5, 6])

In [28]:
# Slicing
a[4:]

array([ 7,  8,  9, 10, 11, 12])

In [29]:
# Slice and assign to a new variable
slice_a = a[0:5]
slice_a

array([3, 4, 5, 6, 7])

You can also assign elements of the array to new values

In [30]:
slice_a[3] = 10
slice_a

array([ 3,  4,  5, 10,  7])

But notice that this actually changes the original array as well!

In [31]:
a

array([ 3,  4,  5, 10,  7,  8,  9, 10, 11, 12])

To avoid this, you can create a copy instead

In [32]:
b = np.arange(3,13)
slice_b = b[0:5].copy()
slice_b[3] = 10

print(slice_b, b)

[ 3  4  5 10  7] [ 3  4  5  6  7  8  9 10 11 12]


### Indexing 2D arrays

The first index of a 2D array is into the rows, and the second index determines the column(s).

In [33]:
# Create a 2D array
mat = np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [34]:
# Select the first row
mat[0]

array([ 5, 10, 20])

In [35]:
# Select the second column 
mat[:, 1]

array([10, 25, 40])

In [36]:
# Select the first and second rows and the second and third columns 
mat[:2, 1:]

array([[10, 20],
       [25, 30]])

In [37]:
# You can reassign multiple elements of the array to the same value
mat[:2, 1:] = 100
mat

array([[  5, 100, 100],
       [ 20, 100, 100],
       [ 35,  40,  10]])

<div class="alert alert-info"><h4>4.</h4><p>In your notebook, experiment with indexing into your arr_2d array:</p></div>

```python
# For example
print("Row 2:", arr_2d[1, :])
print("Last column:", arr_2d[:, -1])
```

<div class="alert alert-info"><h4>5.</h4><p>In a new code cell, create a new array by indexing into your previous one:</p></div>

```python
new_arr = arr_2d[1,2:5]
print(new_arr)
```

<div class="alert alert-info"><h4>6.</h4><p>Assign some of the values of this new array to a random integer</p></div>

```python
new_arr[1:] = np.random.randint(9)
print(new_arr)
```

<div class="alert alert-info"><h4>7.</h4><p>Take a look at your original array as well...</p></div>

```python
print(arr_2d)
```

### Operations

NumPy provides a variety of operations that can be performed on arrays and also between arrays:

In [38]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array operations
arr_sum = arr_2d + 2
arr_product = arr_2d * 2
arr_squared = arr_2d ** 2
arr_sqrroot = np.sqrt(arr_2d)

print("arr_2d plus 2:\n")
print(arr_sum)

print("\n\narr_2d times 2:\n")
print(arr_product)

print("\n\narr_2d squared:\n")
print(arr_squared)

print("\n\narr_2d square rooted:\n")
print(arr_sqrroot)

arr_2d plus 2:

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


arr_2d times 2:

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


arr_2d squared:

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


arr_2d square rooted:

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


<div class="alert alert-info"><h4>7.</h4><p>Add the following code to your notebook:</p></div>

```python
# Create a random array of the same shape as our original one
print('Original:\n', arr_2d)

arr_2d_rand = np.random.randint(1,10,arr_2d.shape)
print('\nRandom:\n', arr_2d_rand)

arr_2d_prod = arr_2d*arr_2d_rand
print('\nProduct between the two:\n', arr_2d_prod)
```

<div class="alert alert-info"><h4>8.</h4><p>What do you notice about the multiplication that you did? What values are multiplied by each other? Include your observations in a Mardown cell in your notebook.</p></div>

# NumPy Basics

Below is a compilation of functions, and NumPy uses that will be helpful when using numpy further. You can also check out the `NumPy Cheat Sheet Data Analysis in Python.pdf` in the Lessons folder. 

### NumPy Basics

| Operator | Description |
|:---- |:---- |
| **`np.array([1,2,3])`**           | **1d array** | 
| **`np.array([(1,2,3),(4,5,6)])`** | **2d array** | 
| **`np.arange(start,stop,step)`**  | **range array**  | 

### Placeholders

| Operator | Description |
|:---- |:---- |
| **`np.linspace(0,2,9)`**      | **Add evenly spaced values btw interval to array of length** |
| **`np.zeros((1,2))`**         | **Create and array filled with zeros** |
| **`np.ones((1,2))`**          | **Creates an array filled with ones** |
| **`np.random.random((5,5))`** | **Creates random array** |
| **`np.empty((2,2))`**         | **Creates an empty array** |

### Array

| Operator | Description |
|:---- |:---- |
| **`array.shape`**        | **Dimensions (Rows,Columns)** |
| **`len(array)`**         | **Length of Array** |
| **`array.ndim`**         | **Number of Array Dimensions** |
| **`array.dtype`**        | **Data Type** |
| **`array.astype(type)`** | **Converts to Data Type** |
| **`type(array)`**        | **Type of Array** |

### Copying/Sorting

| Operator | Description |
|:---- |:---- |
| **`np.copy(array)`**       | **Creates copy of array** |
| **`other = array.copy()`** | **Creates deep copy of array** |
| **`array.sort()`**         | **Sorts an array** |
| **`array.sort(axis=0)`**   | **Sorts axis of array** |

## Array Manipulation

### Adding or Removing Elements

| Operator | Description |
|:---- |:---- |
| **`np.append(a,b)`**               | **Append items to array** |
| **`np.insert(array, 1, 2, axis)`** | **Insert items into array at axis 0 or 1** |
| **`np.resize((2,4))`**             | **Resize array to shape(2,4)** |
| **`np.delete(array,1,axis)`**      | **Deletes items from array** |

### Combining Arrays

| Operator | Description |
|:---- |:---- |
| **`np.concatenate((a,b),axis=0)`** | **Split an array into multiple sub-arrays.** |
| **`np.vstack((a,b))`**             | **Split an array in sub-arrays of (nearly) identical size** |
| **`np.hstack((a,b))`**             | **Split the array horizontally at 3rd index** |

### More

| Operator | Description |
|:---- |:---- |
| **`other = ndarray.flatten()`**       | **Flattens a 2d array to 1d** |
| **`array = np.transpose(other)`**     | **Transpose array** |
| **`array.T`**                         | **Transpose array** |
| **`inverse = np.linalg.inv(matrix)`** | **Inverse of a given matrix** |

## Slicing and Subsetting

| Operator | Description |
|:---- |:---- |
| **`array[i]`**        | **1d array at index i** |
| **`array[i,j]`**      | **2d array at index[i][j]** |
| **`array[i<4]`**      | **Boolean Indexing, see Tricks** |
| **`array[0:3]`**      | **Select items of index 0, 1 and 2** |
| **`array[0:2,1]`**    | **Select items of rows 0 and 1 at column 1** |
| **`array[:1]`**       | **Select items of row 0 (equals array[0:1, :])** |
| **`array[1:2, :]`**   | **Select items of row 1** |
| **`[comment]: <> (`** | **array[1,...]** |
| **`array[ : :-1]`**   | **Reverses array** |

## Mathematics

### Operations

| Operator | Description |
|:---- |:---- |
| **`np.add(x,y)`**        | **Addition** |
| **`np.substract(x,y)`**  | **Subtraction** |
| **`np.divide(x,y)`**     | **Division** |
| **`np.multiply(x,y)`**   | **Multiplication** |
| **`np.sqrt(x)`**         | **Square Root** |
| **`np.sin(x)`**          | **Element-wise sine** |
| **`np.cos(x)`**          | **Element-wise cosine** |
| **`np.log(x)`**          | **Element-wise natural log** |
| **`np.dot(x,y)`**        | **Dot product** |
| **`np.roots([1,0,-4])`** | **Roots of a given polynomial coefficients** |

### Comparison

| Operator | Description |
|:----: |:---- |
| **`==`** | **Equal** |
| **`!=`** | **Not equal** |
| **`<`**  | **Smaller than** |
| **`>`**  | **Greater than** |
| **`<=`** | **Smaller than or equal** |
| **`>=`** | **Greater than or equal** |
| **`np.array_equal(x,y)`** | **Array-wise comparison** |

## Basic Statistics

| Operator | Description |
|:---- |:---- |
| **`np.mean(array)`**   | **Mean** |
| **`np.median(array)`** | **Median** |
| **`array.corrcoef()`** | **Correlation Coefficient** |
| **`np.std(array)`**    | **Standard Deviation** |

### More

| Operator | Description |
|:---- |:---- |
| **`array.sum()`**          | **Array-wise sum** |
| **`array.min()`**          | **Array-wise minimum value** |
| **`array.max(axis=0)`**    | **Maximum value of specified axis** |
| **`array.cumsum(axis=0)`** | **Cumulative sum of specified axis** |

## Challenge

**1. Download `Challenge_33.ipynb` from Teams.**

**2. Upload this file into your own *Project* on Deepnote by dragging the `Challenge_33.ipynb` file onto the Notebooks tab on the left-hand side.** 

**3. Use this notebook to complete Challenge 33 in Deepnote.**