> *The creation of the lessons in this unit relied heavily on the existing lessons created by Mrs. FitzZaland as well as the [lecture series](https://github.com/milaan9/09_Python_NumPy_Module) produced by Dr. Milaan Parmar. Additionally, these lessons have largely been modelled off of the book [Think Python](https://open.umn.edu/opentextbooks/textbooks/43) by Allen Downey.*

# Python NumPy

In this lesson, you will learn various NumPy concepts like how to install NumPy, arrays, functions, matrix multiplication, etc. This NumPy in Python tutorial will help you learn all Python NumPy basics.

**If you'd like, you can check out [this video](https://www.youtube.com/watch?v=xECXZ3tyONo) on NumPy.**

**[Numpy](http://www.numpy.org/)** (‘Numerical Python’) is the core open source library for scientific computing in Python. It is a Linear Algebra Library for Python, it is so important for Finance with Python. It is a very useful library to perform mathematical and statistical operations in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. In this part, we will review the essential functions that you need to know for the tutorial on 'TensorFlow.'

## Why use NumPy?

NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping. On top of that, NumPy is fast. In fact, TensorFlow and Scikit learn to use NumPy array to compute the matrix multiplication in the back end.

# Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## NumPy Array Types:

<div>
<img src="images/array.png" width="700"/>
</div>

## Create a NumPy Array

Simplest way to create an array in Numpy is to use Python List

### Load in NumPy Library

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

To convert python list to a numpy array by using the object **`np.array`**.

In [3]:
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4])

In practice, there is no need to declare a Python List. The operation can be combined.

In [4]:
my_list1  = np.array([1,2,3,4])
my_list1

array([1, 2, 3, 4])

>**NOTE:** Numpy documentation states use of **`np.ndarray`** to create an array. However, this the recommended method

You can also create a numpy array from a Tuple

In [5]:
my_list2 = np.array(range(1,5))
my_list2

array([1, 2, 3, 4])

## Numpy Array basics 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets **`[]`**:

In [6]:
a = np.array([1,2,3]) # Create a 1D array
print(a) 
print(type(a))  # Prints "<class 'numpy.ndarray'>"

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # Create a 2D array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Create a 2D array with 3 rows
my_matrix = np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Get Dimension
my_matrix.ndim

2

In [10]:
# Get Shape
my_matrix.shape

(3, 3)

You can read all about numpy datatypes in this **[documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)**.

### Random number

#### `rand`
Random values in a given shape from a uniform distribution over [0, 1)

In [11]:
# Generate 3 random numbers
np.random.rand(3)

array([0.16707999, 0.07703355, 0.98187932])

In [12]:
# Generate a 2D array of random numbers
np.random.rand(3,5)

array([[0.77425285, 0.83922238, 0.34417499, 0.36124115, 0.53910694],
       [0.01732124, 0.18540371, 0.21901847, 0.28644021, 0.54559845],
       [0.033953  , 0.23105084, 0.56778174, 0.42112556, 0.6119045 ]])

#### `randint`
Return random integers from **low** (inclusive) to **high** (exclusive).

In [13]:
np.random.randint(2,100)

34

In [14]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0, -4,  6],
       [-3, -3,  4],
       [ 5,  5,  6]])

### Array Attributes and Methods


In [15]:
rana = np.random.randint(1,10,8)
rana

array([6, 8, 8, 8, 1, 3, 7, 3])

#### `max`, `min`, `argmax`, `argmin`

In [16]:
rana

array([6, 8, 8, 8, 1, 3, 7, 3])

In [17]:
rana.max()

8

In [18]:
rana.argmax()

1

In [19]:
rana.min()

1

In [20]:
rana.argmin()

4

### Numpy also provides many functions to create arrays:

In [21]:
# Generating Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
# All 0s matrix
np.zeros((2,3))  # pass a tupple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# Generating Zeros
np.ones(3)       # one function

array([1., 1., 1.])

In [24]:
# Generate an array of 5s
np.ones(3)*5

array([5., 5., 5.])

In [25]:
# Generate a 2D array of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Array indexing

Numpy offers several ways to index into arrays and accessing/changing specific elements, rows, columns, etc.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [27]:
# Generate a 1D array
a = np.arange(3,13)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
# Integer indexing
a[1]

4

In [29]:
# Slicing
a[1:4]

array([4, 5, 6])

In [30]:
# Slicing
a[:4]

array([3, 4, 5, 6])

In [31]:
# Slicing
a[4:]

array([ 7,  8,  9, 10, 11, 12])

In [32]:
# Slice and assign to a new variable
slice_a = a[0:5]
slice_a

array([3, 4, 5, 6, 7])

You can also assign elements of the array to new values

In [33]:
slice_a[3] = 10
slice_a

array([ 3,  4,  5, 10,  7])

But notice that this actually changes the original array as well!

In [34]:
a

array([ 3,  4,  5, 10,  7,  8,  9, 10, 11, 12])

To avoid this, you can create a copy instead

In [35]:
b = np.arange(3,13)
slice_b = b[0:5].copy()
slice_b[3] = 10

print(slice_b, b)

[ 3  4  5 10  7] [ 3  4  5  6  7  8  9 10 11 12]


### Indexing 2D arrays

The first index of a 2D array is into the rows, and the second index determines the column(s).

In [36]:
# Create a 2D array
mat = np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [37]:
# Select the first row
mat[0]

array([ 5, 10, 20])

In [38]:
# Select the second column 
mat[:, 1]

array([10, 25, 40])

In [39]:
# Select the first and second rows and the second and third columns 
mat[:2, 1:]

array([[10, 20],
       [25, 30]])

In [40]:
# You can reassign multiple elements of the array to the same value
mat[:2, 1:] = 100
mat

array([[  5, 100, 100],
       [ 20, 100, 100],
       [ 35,  40,  10]])

# NumPy Basics

Below is a compilation of functions, and NumPy uses that will be helpful when using numpy further. You can also check out the `NumPy Cheat Sheet Data Analysis in Python.pdf` in the Lessons folder. 

### NumPy Basics

| Operator | Description |
|:---- |:---- |
| **`np.array([1,2,3])`**           | **1d array** | 
| **`np.array([(1,2,3),(4,5,6)])`** | **2d array** | 
| **`np.arange(start,stop,step)`**  | **range array**  | 

### Placeholders

| Operator | Description |
|:---- |:---- |
| **`np.linspace(0,2,9)`**      | **Add evenly spaced values btw interval to array of length** |
| **`np.zeros((1,2))`**         | **Create and array filled with zeros** |
| **`np.ones((1,2))`**          | **Creates an array filled with ones** |
| **`np.random.random((5,5))`** | **Creates random array** |
| **`np.empty((2,2))`**         | **Creates an empty array** |

### Array

| Operator | Description |
|:---- |:---- |
| **`array.shape`**        | **Dimensions (Rows,Columns)** |
| **`len(array)`**         | **Length of Array** |
| **`array.ndim`**         | **Number of Array Dimensions** |
| **`array.dtype`**        | **Data Type** |
| **`array.astype(type)`** | **Converts to Data Type** |
| **`type(array)`**        | **Type of Array** |

### Copying/Sorting

| Operator | Description |
|:---- |:---- |
| **`np.copy(array)`**       | **Creates copy of array** |
| **`other = array.copy()`** | **Creates deep copy of array** |
| **`array.sort()`**         | **Sorts an array** |
| **`array.sort(axis=0)`**   | **Sorts axis of array** |

## Array Manipulation

### Adding or Removing Elements

| Operator | Description |
|:---- |:---- |
| **`np.append(a,b)`**               | **Append items to array** |
| **`np.insert(array, 1, 2, axis)`** | **Insert items into array at axis 0 or 1** |
| **`np.resize((2,4))`**             | **Resize array to shape(2,4)** |
| **`np.delete(array,1,axis)`**      | **Deletes items from array** |

### Combining Arrays

| Operator | Description |
|:---- |:---- |
| **`np.concatenate((a,b),axis=0)`** | **Split an array into multiple sub-arrays.** |
| **`np.vstack((a,b))`**             | **Split an array in sub-arrays of (nearly) identical size** |
| **`np.hstack((a,b))`**             | **Split the array horizontally at 3rd index** |

### More

| Operator | Description |
|:---- |:---- |
| **`other = ndarray.flatten()`**       | **Flattens a 2d array to 1d** |
| **`array = np.transpose(other)`**     | **Transpose array** |
| **`array.T`**                         | **Transpose array** |
| **`inverse = np.linalg.inv(matrix)`** | **Inverse of a given matrix** |

## Slicing and Subsetting

| Operator | Description |
|:---- |:---- |
| **`array[i]`**        | **1d array at index i** |
| **`array[i,j]`**      | **2d array at index[i][j]** |
| **`array[i<4]`**      | **Boolean Indexing, see Tricks** |
| **`array[0:3]`**      | **Select items of index 0, 1 and 2** |
| **`array[0:2,1]`**    | **Select items of rows 0 and 1 at column 1** |
| **`array[:1]`**       | **Select items of row 0 (equals array[0:1, :])** |
| **`array[1:2, :]`**   | **Select items of row 1** |
| **`[comment]: <> (`** | **array[1,...]** |
| **`array[ : :-1]`**   | **Reverses array** |

## Mathematics

### Operations

| Operator | Description |
|:---- |:---- |
| **`np.add(x,y)`**        | **Addition** |
| **`np.substract(x,y)`**  | **Subtraction** |
| **`np.divide(x,y)`**     | **Division** |
| **`np.multiply(x,y)`**   | **Multiplication** |
| **`np.sqrt(x)`**         | **Square Root** |
| **`np.sin(x)`**          | **Element-wise sine** |
| **`np.cos(x)`**          | **Element-wise cosine** |
| **`np.log(x)`**          | **Element-wise natural log** |
| **`np.dot(x,y)`**        | **Dot product** |
| **`np.roots([1,0,-4])`** | **Roots of a given polynomial coefficients** |

### Comparison

| Operator | Description |
|:----: |:---- |
| **`==`** | **Equal** |
| **`!=`** | **Not equal** |
| **`<`**  | **Smaller than** |
| **`>`**  | **Greater than** |
| **`<=`** | **Smaller than or equal** |
| **`>=`** | **Greater than or equal** |
| **`np.array_equal(x,y)`** | **Array-wise comparison** |

## Basic Statistics

| Operator | Description |
|:---- |:---- |
| **`np.mean(array)`**   | **Mean** |
| **`np.median(array)`** | **Median** |
| **`array.corrcoef()`** | **Correlation Coefficient** |
| **`np.std(array)`**    | **Standard Deviation** |

### More

| Operator | Description |
|:---- |:---- |
| **`array.sum()`**          | **Array-wise sum** |
| **`array.min()`**          | **Array-wise minimum value** |
| **`array.max(axis=0)`**    | **Maximum value of specified axis** |
| **`array.cumsum(axis=0)`** | **Cumulative sum of specified axis** |

## Challenge

**1. Download `Challenge_33.ipynb` from Teams.**

**2. Upload this file into your own *Project* on Deepnote by dragging the `Challenge_33.ipynb` file onto the Notebooks tab on the left-hand side.** 

**3. Use this notebook to complete Challenge 33 in Deepnote.**